config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root "boards#index" # login は home#index

  get "login", to: "home#index"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "followings", to: "user_relations#followings"
  get "followers", to: "user_relations#followers"

  resources :boards do
    resources :favorites, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy]
  resources :tags, only: %i[index create destroy]
  resources :users
  resources :user_relations, only: %i[create destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  image           :string
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#
class User < ApplicationRecord
  has_secure_password

  # user_imageの設定
  mount_uploader :image, ImageUploader
  
  # controllerで使える。 active_relationships.find_by(followed_id: 1, ...)
  # フォローをする関係
  has_many :active_relationships,       # 今つけた名前
            class_name: "UserRelation", # テーブルを参照
            foreign_key: "follower_id", # このカラムを使う
            dependent: :destroy         # ユーザー消したら関連も消えるよ

  # フォロワーの関係
  has_many :passive_relationships,      # 今つけた名前
            class_name: "UserRelation", # テーブルを参照
            foreign_key: "followed_id", # このカラムを使う
            dependent: :destroy         # ユーザー消したら関連も消えるよ
  

  # 一覧画面で使用できるようにする user.followers で使える
  has_many :followings,
            through: :active_relationships,
            source: :followed # followingsはfollowed idの集合体

  has_many :followers,
            through: :passive_relationships,
            source: :follower  # followingsはfollower idの集合体
  
  # いいねの関係
  has_many :favorites, dependent: :delete_all

  # 上の記述により使えるメソッド
  # active_relationships.follower フォロワーを返す
  # active_relationships.followed　フォローしてるユーザーを返す
  # user.active_relationships.create(followed_id: user_id)　登録する
  # user.following.include?(user)
  # user.following.find(user)

  validates :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 16 },
    format: {
      with: /\A[a-z0-9]+\z/,
      message: "は小文字英数字で入力してください"
    }
  
  validates :password,
    # uniqueness: trueをつけるとエラー
    length: { minimum: 6, maximum: 30}


  # フォローする
  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  # フォロー解除
  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  # 現在のユーザーがフォローしてるか
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :check_current_user, only: %i[edit update]

  def index
    @q = User.all.ransack(params[:q])
    @users = @q.result(distinct: true)
    session[:user_name] = nil
  end
  
  def show
    session[:user] = nil
    session[:user_name] = nil
    if @user == current_user
      @boards = Board.where(name: @user.name).order(id: "DESC")
    else
      @boards = Board.where(name: @user.name).where(published: true).order(id: "DESC")
    end
    session[:user] = @user # ユーザーのフォロー、フォロワー一覧で使う
  end
  
  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user.id), flash: { notice: "ユーザーを登録しました" }
    else
      redirect_to new_user_path, flash: {
        user: user,
        error: user.errors.full_messages
      }
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, flash: { notice: "#{@user.name}の更新に成功しました" }
    else
      redirect_to request.referer, flash: { error: "#{@user.name}の更新に失敗しました" }
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :image)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def check_current_user
      redirect_to boards_path, flash: { error: "そのユーザーは編集出来ません。" } if @user != current_user
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- ユーザー登録form -->
<%= form_with model: @user, local: true, class: "" do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "" %>
    <%= f.text_field :name, class: "form-input" %>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "" %>
    <%= f.password_field :password, class: "form-input" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "" %>
    <%= f.password_field :password_confirmation, class: "form-input" %>
  </div>
  <%= f.submit "作成", class: "primary-btn float-right" %>
<% end %>

app/views/users/_login_form.html.erb
<%= form_with scope: :session, url: login_path, class: "" do |f| %>
  <div class="form-group">
    <%= f.label :name, "ユーザー名", class: "" %>
    <%= f.text_field :name, class: "form-input", autofocus: true, required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password, "パスワード", class: "" %>
    <%= f.password_field :password, class: "form-input", required: true %>
  </div>
  <%= f.submit "ログイン", class: "primary-btn float-right" %>
<% end %>

app/views/users/edit.html.erb
<h1 class="font-bold">ユーザー編集</h1>

<%= render partial: "form", locals: { user: @user } %>

app/views/users/index.html.erb
<div>
  <div class="mb-10 flex flex-col justify-between sm:flex-row">
    <h1 class="font-bold mb-4">ユーザー一覧</h1>
    <div>
      <%= search_form_for @q, url: users_path do |f| %>
        <div class="flex gap2 justify-center">
          <div>
            <%= f.text_field :name_cont, placeholder: "ユーザー名", class: "form-input" %>
          </div>
          <div class="inline" ><%= f.submit "検索", class: "secondary-btn" %></div>
        </div>
      <% end %>
    </div>
  </div>

  <%= render "user_relations/users" %>
  <% breadcrumb :user_path %>
</div>

app/views/users/new.html.erb
<h1 class="font-bold">ユーザー登録</h1>

<%= render partial: "form", locals: { user: @user } %>

app/views/users/show.html.erb
<div>
  <% breadcrumb :user_path_show, @user %>

  <div class="py-4 mb-10">
    <div class="flex justify-between items-center">
      <div class="flex gap-3 items-center">
        <div class="w-[70px] h-[70px]"><%= image_tag @user.image_url, class: 'rounded-full w-full h-full' %></div>
        <%= link_to @user do %>
          <div class="mr-2 text-2xl font-bold flex items-center"><%= @user.name %></div>
        <% end %>
      </div>
      
      <% if @user != @current_user %>
        <div class="flex">
          <% if @current_user.following?(@user) %>
            <%= button_to "フォロー外す", user_relation_path(@user.id), method: :delete, class: "primary-btn opacity-60 z-10" %>
          <% else %>
            <%= button_to "フォローする", user_relations_path(@user.id), method: :post, class: "primary-btn z-10" %>
          <% end %>
        </div>
      <% else %>
        <%= link_to "編集", edit_user_path, class: "px-4 py-1 border border-black rounded-full duration-300 hover:bg-black hover:text-white" %>
      <% end %>
    </div>

    <div class="flex gap-4 mt-4">
      <%= link_to followings_path(@user.id) do %>
        <p>
          <span class="mr-1 font-bold text-2xl">
            <%= @user.followings.count %>
          </span>フォロー中
        </p>
      <% end %>
      <%= link_to followers_path(@user.id) do %>
        <p>
          <span class="mr-1 font-bold text-2xl">
            <%= @user.followers.count %>
          </span>フォロワー
        </p>
      <% end %>
    </div>
  </div>

  <% if @boards.present? %>
    <div class="py-2 mb-2 bg-black text-white text-center">投稿一覧</div>
    <%= render "shared/boards" %>
  <% else %>
    <div class="my-4">投稿はありません</div>
  <% end %>
</div>