config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root "boards#index" # login は home#index

  get "login", to: "home#index"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "followings", to: "user_relations#followings"
  get "followers", to: "user_relations#followers"

  resources :boards do
    resources :favorites, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy]
  resources :tags, only: %i[index create destroy]
  resources :users
  resources :user_relations, only: %i[create destroy]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text
#  name       :string
#  published  :boolean          default(TRUE)
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Board < ApplicationRecord
  # commentは一体多, tagsは多対多, board_tag_relationは、中間テーブル
  # dependentは、関連しているものが削除された時に消す

  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations
  has_many :favorites, dependent: :delete_all

  validates :name, presence: true, length: {maximum: 20}
  validates :title, presence: true, length: {maximum: 30}
  validates :body, presence: true, length: {maximum: 500}

  # いいねを確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/views/shared/_boards.html.erb
<% @boards.each do |board|  %>
  <div class="flex text-[16px]">
    <!-- urlに/usersが含まれて、usersが自分のではない -->
    <div class="<%=request.path.match(/\/users(\/)?/) && !(request.path.match(/\/#{@current_user.id}(\/)?/)) ? 
      "max-w-[800px]" : "sm:w-[89.9%] md:w-[91.6%] lg:w-[92.5%] max-w-[800px]" %>"
    >
      <%= link_to board do %>
        <ul class="p-2 grid grid-cols-4 text-center font-bold <%= "bg-gray-300" if board.published == false %> hover:bg-gray-300 border-b-2">
          <li><%= board.id %></li>
          <li><%= board.title %></li>
          <li><%= board.name %></li>
          <li><%= board.created_at.to_s(:datetime_jp) %></li>
        </ul>
      <% end %>
    </div>
    
    <% if @current_user.present? && board.name == @current_user.name %>
      <div class="hidden sm:block mt-4 text-md">
        <%= button_to "削除", board, method: :delete, class: "danger-btn font-bold" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_comment_form.html.erb
<div>
  <section class="mt-10">
    <p class="mb-4 font-bold">コメント記入</p>
    <%= form_with model: @comment, local: true do |f| %>
      <%= f.hidden_field :board_id %> <!-- なぜこれで送れる？表示しないで送信するデータ -->
      <div class="form-group">
        <% if @current_user %>
          <%= f.hidden_field :name, value: @current_user.name %>
        <% else %>
          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: "form-input" %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :comment, "コメント" %>
        <%= f.text_area :comment, class: "form-input" %>
      </div>
      <div>
        <%= f.submit "保存", class: "primary-btn" %>
      </div>
    <% end %>
  </section>
</div>

app/views/shared/_comments.html.erb
<section>
  <% if @board.comments.count > 0 %>
    <h2 class="mt-14 font-bold">コメント</h2>

    <% @board.comments.each do |comment| %>
      <div class="flex justify-between">
        <div class="p-4 mb-4 w-full border-b-2">
          <%= simple_format(comment.comment) %>
          <div class="flex justify-end gap-4 text-sm ">
            <p><%= comment.name %></p>
            <p><%= comment.created_at.to_s(:datetime_jp) %></p>
          </div>
        </div>

        <% if @current_user.present? && comment.name == @current_user.name %>
          <div class="mt-4 w-[100px] sm:w-[80px] text-md">
            <%= button_to "削除", comment, method: :delete, data: { confirm: "削除してもよろしいですか？", disable_with: 'loading...'}, class: "danger-btn" %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="p-4 mb-10 w-full font-bold bg-green-300 border-2 border-green-400 rounded"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error].instance_of?(Array) %>
  <ul class="p-4 mb-10 w-full font-bold bg-red-300 border-2 border-red-400 rounded">
    <% flash[:error].each do |msg| %>
      <li class="mb-2"><%= msg %></li>
    <% end %>
  </ul>
<% elsif flash[:error] %>
  <p class="p-4 mb-10 w-full font-bold bg-red-300 border-2 border-red-400 rounded"><%= flash[:error] %></p>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @board, local: true do |f| %>
  <div class="form-group">
    <% if @current_user.present? %>
      <%= f.hidden_field :name, value: @current_user.name %>
    <% else %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: "form-input", autofocus: true, required: true, maxlength: "20"%>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <% if @current_user.present? %>
      <%= f.text_field :title, class: "form-input", required: true, maxlength: "30", autofocus: true %>
    <% else %>
      <%= f.text_field :title, class: "form-input", required: true, maxlength: "30" %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-input", rows: 10, required: true, maxlength: "500" %>
  </div>

  <!-- タグ -->
  <div>
    <p>タグ</p>
    <ul class="flex flex-wrap gap-2">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <%= tag.label class: "" do %>
          <%= tag.check_box class: "" %>
          <%= tag.text %>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div>
    <label><%= f.radio_button :published, true %>公開</label>
    <label><%= f.radio_button :published, false %>非公開</label>
  </div>

  <div class="mt-4">
    <%= f.submit "#{request.url&.include?("edit") ? "更新" : "投稿"}", class: "primary-btn float-right" %>
  </div>
<% end %>