config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root "boards#index" # login は home#index

  get "login", to: "home#index"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "followings", to: "user_relations#followings"
  get "followers", to: "user_relations#followers"

  resources :boards do
    resources :favorites, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy]
  resources :tags, only: %i[index create destroy]
  resources :users
  resources :user_relations, only: %i[create destroy]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text
#  name       :string
#  published  :boolean          default(TRUE)
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Board < ApplicationRecord
  # commentは一体多, tagsは多対多, board_tag_relationは、中間テーブル
  # dependentは、関連しているものが削除された時に消す

  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations
  has_many :favorites, dependent: :delete_all

  validates :name, presence: true, length: {maximum: 20}
  validates :title, presence: true, length: {maximum: 30}
  validates :body, presence: true, length: {maximum: 500}

  # いいねを確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_board, only: %i[show edit update destroy]

  def index
    # タグの選択
    session[:tag_id] = nil if params[:all].present? # タグで絞り込むで全表示は諦めて、全表示ボタンを作成
    session[:tag_id] = params[:tag_id] if params[:tag_id].present? && session[:tag_id] != params[:tag_id] # paramsが来て、sessionと違うならsessionを更新

    if session[:tag_id].present?
      @q = Tag.find(session[:tag_id]).boards.where(published: true).page(params[:page]).order("#{sort_column} #{sort_direction}").ransack(params[:q])
      @boards = @q.result(distinct: true)
    else
      @q = Board.page(params[:page]).where(published: true).order("#{sort_column} #{sort_direction}").ransack(params[:q])  # タグ検索追加(タグで絞りこむで全表示)
      @boards = @q.result(distinct: true)
    end
  end

  def new
    @board = Board.new(flash[:board]) # createに失敗した時、入力データを保持
  end

  def create
    # ログインしていないユーザーは、登録してる名前を使えない
    if User.find_by(name: params[:board][:name]) && @current_user.nil?
      redirect_to new_board_path, flash: {
        board: board_params, # newに渡す
        error: "そのユーザーは既に存在します"
      }
    else
      board =  Board.new(board_params)
      # 成功
      if board.save
        flash[:notice] = "「#{params[:board][:title]}」の掲示板を作成しました。"
        redirect_to boards_path
      else 
        redirect_to new_board_path, flash: {
          board: board,
          error: board.errors.full_messages
        }
      end
    end
  end
  
  def show
    # @comment = @board.comments.new # これはboardの方のcomment。知らぬ間にsaveされるから、空のまま使われる。よくないから消す
    @comment = Comment.new(board_id: @board.id)
    @user = User.find_by(name: @board.name)
    flash[:follow_user_name] = @board.name
    session[:board_title] = nil
    session[:board_id] = nil
  end

  def edit
    if @current_user.nil? || @board.name != @current_user.name
      flash[:error] = "この投稿は編集できません"
      redirect_to boards_path
    end
  end

  # 普通にboardを更新する or いいね
  def update
    if @board.update(board_params)
      flash[:notice] = "「#{@board.title}」 の掲示板を更新しました。"
      redirect_to boards_path
    else
      flash[:board] = board_params
      flash[:error] = @board.errors.full_messages
      redirect_back(fallback_location: boards_path)
    end
  end
  
  def destroy
    if @current_user.present? && @board.name == @current_user.name
      @board.destroy # deleteでもいける
      redirect_to boards_path, flash: { error: "「#{@board.title}」 の掲示板を削除しました。" }
    else
      flash[:error] = "この投稿は削除できません"
      redirect_to request.referer
    end
  end

  private
  
  def board_params
    params.require(:board).permit(:name, :title, :body, :published, tag_ids: [])
  end

  def set_board
    @board = Board.find(params[:id])
  end

  # paramsに asc・descが無いなら、ascを返す
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end
  
  # Boardのカラムに含まれていないなら、初期値でidでソート
  def sort_column  
    Board.column_names.include?(params[:column]) ? params[:column] : 'id'
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def sort_order(column, title)
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title , { column: column, direction: direction }
  end
end

app/views/boards/edit.html.erb
<div class="flex justify-between items-center">
  <% breadcrumb :edit_board_path %>
  <h1 class="font-bold">掲示板編集</h1>
  <%= link_to "掲示板一覧", boards_path, class: "secondary-btn" %>
</div>

<%= render "shared/form" %>

app/views/boards/index.html.erb
<div>
  <section class="mb-4">
    <div class=" flex justify-between items-center">
      <% breadcrumb :boards_path %>
      <h1 class="font-bold">
        掲示板一覧
      </h1>
      <%= link_to "掲示板作成", new_board_path, class: "secondary-btn"%>
      </div>
    </div>

    <div class="flex flex-col justify-center items-center lg:flex-row lg:justify-between">
      <div class="flex gap-4 justify-center">
        <!-- タグ検索 -->
        <%= form_tag boards_path, method: :get, class: "p-1 border-2 border-gray-300 rounded" do %>
          <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
            {
              prompt: "タグで絞り込む", # 何も選択していない時表示
              class: "cursor-pointer",
              onchange: "submit(this.form);" # onchange変更される度に実行(ここではsubmit)
            }
          %>
        <% end %>

        <!-- 全表示ボタン -->
        <%= form_with scope: :all, url:boards_path, local: true, method: :get do |f| %>
          <%= f.hidden_field :all, value: 1 %>
          <%= f.submit "全表示", class: "p-1 border-2 border-gray-300 rounded cursor-pointer" %>
        <% end %>
        <div class="w-[57px] sm:w-0"></div>
      </div>

      <div class="mt-4 lg:mt-0">
        <%= search_form_for @q, url: boards_path do |f| %>
          <div class="flex gap-2 justify-center items-center sm:flex-row sm:justify-end">
            <div class="flex flex-col gap-2 sm:flex-row">
              <div><%= f.text_field :title_cont, placeholder: "タイトル", class: "form-input" %></div>
              <div><%= f.text_field :name_cont, placeholder: "制作者", class: "form-input" %></div>
            </div>
            <div class="inline" ><%= f.submit "検索", class: "secondary-btn" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

  <section class="mt-6 sm:w-[89.9%] md:w-[91.6%] lg:w-[92.5%]">
    <ul class="p-2 grid grid-cols-4 text-center bg-black text-white text-sm sm:text-xl font-bold">
      <li><%= sort_order "id", "ID" %></li>
      <li><%= sort_order "title", "タイトル" %></li>
      <li><%= sort_order "name", "作成者" %></li>
      <li><%= sort_order "created_at", "作成日時" %></li>
    </ul>
  </section>

  <section>
    <%= render "shared/boards" %>
  </section>

  <%= paginate @boards %>
</div>

app/views/boards/new.html.erb
<div class="flex justify-between items-center">
  <% breadcrumb :new_board_path %>
  <h1 class="font-bold">掲示板作成</h1>
  <%= link_to "掲示板一覧", boards_path, class: "secondary-btn" %>
</div>

<%= render "shared/form"%>

app/views/boards/show.html.erb
<div>
  <% breadcrumb :boards_path_show, @board %>
  <div class="<%='mt-4 flex justify-between items-center' if @user.present? && @current_user.present?%>">
    <!-- ユーザーへのリンク、フォローボタン -->
      <div class="flex justify-start items-center gap-3">
        <% if @user.present? %>
          <div class="w-[70px] h-[70px]"><%= image_tag @user.image_url, class: 'rounded-full w-full h-full' %></div>
            <%= link_to @user.name, @user, class: "mr-2 text-2xl font-bold flex items-center" %>
            <% if @current_user.present? && @user != @current_user %>
              <% if @current_user.following?(@user) %>
                <%= button_to "フォロー外す", user_relation_path(@user.id), method: :delete, class: "primary-btn opacity-60" %>
              <% else %>
                <%= button_to "フォローする", user_relations_path(@user.id), method: :post, class: "primary-btn" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

    <div class="flex gap-3 justify-end">
      <div><%= link_to "一覧",boards_path, class: "secondary-btn" %></div>
      <% if @current_user.present? && @board.name == @current_user.name %>
        <div><%= link_to "編集", edit_board_path, class: "secondary-btn" %></div>
      <% end %>
    </div>
  </div>
  
  <!-- boardのタイトル、タグ、本文 -->
  <section>
    <div class="mt-10 font-bold w-90 border-2 border-gray-300">
      <div class="p-4 bg-gray-100 text-3xl">
        <%= @board.title %>
        <% if @board.published == false %>
          <span class="danger-btn text-xl">非公開</span>
        <% end %>
        <% if @board.tags.present? %>
          <ul class="flex flex-wrap gap-2 mt-2">
            <% @board.tags.each do |tag| %>
              <li class="inline px-2 py-1 bg-blue-500 text-white text-sm rounded"><%= tag.name %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="p-4 text-md"><%= simple_format(@board.body) %></div>
      <p class="p-4 flex justify-end text-sm"><%= @board.name %></p>
    </div>

    <div class="<%='flex justify-between' if @user.present? && @current_user.present? && @user != @current_user%>">
      <% if @user.present? && @current_user.present? && @user != @current_user %> <%# 投稿者は登録していて自分ではない %>
        <!-- いいね -->
        <% if @board.favorited_by?(@current_user) %>
          <%= button_to board_favorite_path(@board.id), method: :delete do %>
            💖<%= @board.favorites.count %> いいね
          <% end %>
        <% else %>
          <%= button_to board_favorites_path(@board.id), method: :post do %>
            ♡<%= @board.favorites.count %> いいね
          <% end %>
        <% end %>
      <% end %>
      <div class="text-sm text-gray-500 text-right">
        <p>作成日：<%= @board.created_at.to_s(:datetime_jp) %></p>
        <p>更新日：<%= @board.updated_at.to_s(:datetime_jp) %></p>
      </div>
    </div>
  </section>

  <% if @current_user.present? && @board.name == @current_user.name %>
    <div class="flex gap-3 justify-end">
      <%= button_to "投稿を削除", @board, method: :delete, class: "danger-btn mt-4" %>
    </div>
  <% end %>
  
  <%= render "shared/comments" %>
  <%= render "shared/comment_form" %> 
</div>