config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root "boards#index" # login は home#index

  get "login", to: "home#index"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "followings", to: "user_relations#followings"
  get "followers", to: "user_relations#followers"

  resources :boards do
    resources :favorites, only: %i[create destroy]
  end
  resources :comments, only: %i[create destroy]
  resources :tags, only: %i[index create destroy]
  resources :users
  resources :user_relations, only: %i[create destroy]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 全てのcontroller, viewで使える
  before_action :current_user

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
# 全ページで使える
module ApplicationHelper
  def header_link_item(name, path)
    class_name = "duration-300 hover:opacity-60"
    # 今のパスと引数のパス同じなら、変数にクラスを追加
    class_name << " opacity-60" if current_page?(path)

    # liタグ内に a タグを埋め込む
    content_tag :li, class: "" do
      link_to name, path, class: class_name
    end
  end
end

app/views/application/_header.html.erb
<header class="py-6 sm:py-8 w-full bg-black text-white flex flex-col justify-center">
  <nav>
    <div class="flex justify-between gap-6 w-[95%] mx-auto max-w-[800px]">
      <div class="flex gap-4">
        <%= link_to "Simple Board", root_path, class: "duration-300 hover:opacity-60" %>
        <ul class="sm:flex gap-4 hidden">
          <li><%= header_link_item("掲示板一覧",boards_path) %></li>
          <li><%= header_link_item("作成",new_board_path) %></li>
          <li><%= header_link_item("タグ",tags_path) %></li>
          <li><%= header_link_item("ユーザー",users_path) %></li>
        </ul>
      </div>

        <!-- ログイン時 -->
      <ul class="flex gap-4">
        <%# <% if session[:user_id].present? %>
        <% if @current_user %>
          <li><%= link_to "マイページ", user_path(@current_user.id), class: "duration-300 hover:opacity-60" %></li>
          <li><%= button_to "ログアウト", logout_path, method: :delete, class: "duration-300 hover:opacity-60" %></li>
        <% else %>
          <li><%= link_to "登録", new_user_path, class: "duration-300 hover:opacity-60" %></li>
          <li><%= link_to "ログイン", login_path, class: "duration-300 hover:opacity-60" %></li>
        <% end %>
      </ul>
    </div>

    <ul class="mt-4 flex sm:hidden gap-4 text-center justify-center">
      <li><%= header_link_item("作成",new_board_path) %></li>
      <li><%= header_link_item("タグ",tags_path) %></li>
      <li><%= header_link_item("ユーザー",users_path) %></li>
    </ul>
  </nav>
</header>